CONTIKI_PROJECT = loramac
MODULES = os/services/at-master arch/cpu/cc2538/dev
PROJECT_SOURCEFILES += loraphy.c
all: $(CONTIKI_PROJECT)

CONTIKI = $(HOME)/contiki-ng
include $(CONTIKI)/Makefile.include