CONTIKI_PROJECT = lorarpl
MODULES = os/services/at-master arch/cpu/cc2538/dev
#MODULES += 
PROJECT_SOURCEFILES += loraphy.c
PROJECT_SOURCEFILES += loramacV2.c
PROJECT_SOURCEFILES += mybuffer.c
all: $(CONTIKI_PROJECT)

CONTIKI = $(HOME)/contiki-ng
include $(CONTIKI)/Makefile.include